services:
  fetcher:
    build: .
    volumes:
      - tailscalederp:/app  # Maps the current working directory to /app in the container
    ports:
      - "8000:8000"
volumes:
  tailscalederp:
    external: true      
